
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Furkan
 */
public class Adminn extends javax.swing.JFrame {

    ArrayList<Admin> Adminler = new ArrayList();
    Admin y1 = new Admin("Furkan", "TULUK", "ft", "ft123");
    Admin y2 = new Admin("Atakan", "Halil", "ah", "ah123");
    Admin y3 = new Admin("Şamil", "İleri", "şi", "şi123");
    AdminPanel ap = new AdminPanel();

    public Adminn() {
        initComponents();
        Adminler.add(y1);
        Adminler.add(y2);
        Adminler.add(y3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Giriş = new javax.swing.JButton();
        Sifre = new javax.swing.JTextField();
        KullaniciAdi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 561, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Giriş.setBackground(new java.awt.Color(51, 204, 255));
        Giriş.setForeground(new java.awt.Color(255, 0, 51));
        Giriş.setIcon(new javax.swing.ImageIcon("C:\\Users\\90538\\Desktop\\icons\\icons8-login-25.png")); // NOI18N
        Giriş.setText("Giriş");
        Giriş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirişActionPerformed(evt);
            }
        });
        jPanel2.add(Giriş, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 313, 133, -1));

        Sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SifreActionPerformed(evt);
            }
        });
        jPanel2.add(Sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 235, 133, -1));

        KullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KullaniciAdiActionPerformed(evt);
            }
        });
        jPanel2.add(KullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 173, 133, -1));

        jLabel2.setText("Şifre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 238, -1, -1));

        jLabel1.setText("Kullanıcı Adı");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 176, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("YÖNETİCİ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setText("Anasayfa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 591, 555));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KullaniciAdiActionPerformed

    private void SifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SifreActionPerformed

    private void GirişActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirişActionPerformed
        String mesaj = "Kullanici adi veya Şifre Hatası!";
        String mesaj2 = "Başarıyla Giriş Yapılmıştır!";
        boolean bulundu = false;                          // boolean ile list kontrolü
        for (Admin y : Adminler) {
            if (KullaniciAdi.getText().equals(y.getKullanıcıAdı()) && Sifre.getText().equals(y.getŞifre())) {    // Kullanıcı adı ve şifre kontrolü
                JOptionPane.showMessageDialog(this, mesaj2, "Mesaj", JOptionPane.INFORMATION_MESSAGE);
                bulundu = true;
                ap.setVisible(true);
                break;
            }

            if (bulundu == false) {

                JOptionPane.showMessageDialog(this, mesaj, "Mesaj", JOptionPane.WARNING_MESSAGE);

            }

        }


    }//GEN-LAST:event_GirişActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Anasayfa a = new Anasayfa();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Giriş;
    private javax.swing.JTextField KullaniciAdi;
    private javax.swing.JTextField Sifre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
