/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Furkan
 */
    import javax.swing.ImageIcon;

public class Anasayfa extends javax.swing.JFrame {
    
    ImageIcon imageadmin = new ImageIcon("C:\\Users\\90538\\Desktop\\icons\\admin.png");
    ImageIcon imageres = new ImageIcon("C:\\Users\\90538\\Desktop\\icons\\reception.png");
    ImageIcon imagedok = new ImageIcon("C:\\Users\\90538\\Desktop\\icons\\doktor.png");
    ImageIcon imageran = new ImageIcon("C:\\Users\\90538\\Desktop\\icons\\randevu.png");
    ImageIcon imageucr = new ImageIcon("C:\\Users\\90538\\Desktop\\icons\\ucret.png");
    Doktor dr = new Doktor();
    Randevular randevu = new Randevular();
    FaturaYazdirma fy = new FaturaYazdirma();
    Adminn ad = new Adminn();
    ResepsiyonGiris giris = new ResepsiyonGiris();
    
    public Anasayfa() {
        initComponents();
        this.setLocationRelativeTo(null);
        labeladm.setIcon(imageadmin);
        labelresp.setIcon(imageres);
        labeldok.setIcon(imagedok);
        labelran.setIcon(imageran);
        labelucr.setIcon(imageucr);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adm = new javax.swing.JButton();
        res = new javax.swing.JButton();
        dok = new javax.swing.JButton();
        ran = new javax.swing.JButton();
        ucr = new javax.swing.JButton();
        labeladmin = new javax.swing.JLabel();
        labelres = new javax.swing.JLabel();
        labeladm = new javax.swing.JLabel();
        labelresp = new javax.swing.JLabel();
        labeldok = new javax.swing.JLabel();
        labelran = new javax.swing.JLabel();
        labelucr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setForeground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 36)); // NOI18N
        jLabel1.setText("HASTANE OTOMASYON SISTEMI");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 110, -1, -1));

        adm.setBackground(new java.awt.Color(102, 255, 255));
        adm.setText("ADMİN");
        adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admActionPerformed(evt);
            }
        });
        jPanel2.add(adm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 120, -1));

        res.setBackground(new java.awt.Color(102, 255, 255));
        res.setText("RESEPSİYON");
        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        jPanel2.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, -1));

        dok.setBackground(new java.awt.Color(102, 255, 255));
        dok.setText("DOKTOR");
        dok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokActionPerformed(evt);
            }
        });
        jPanel2.add(dok, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 120, -1));

        ran.setBackground(new java.awt.Color(102, 255, 255));
        ran.setText("RANDEVU");
        ran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ranActionPerformed(evt);
            }
        });
        jPanel2.add(ran, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 120, -1));

        ucr.setBackground(new java.awt.Color(102, 255, 255));
        ucr.setText("HASTANE ÜCRETİ");
        ucr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucrActionPerformed(evt);
            }
        });
        jPanel2.add(ucr, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 120, -1));
        jPanel2.add(labeladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 292, -1, -1));
        jPanel2.add(labelres, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 292, -1, -1));

        labeladm.setForeground(new java.awt.Color(153, 255, 255));
        labeladm.setText(".");
        jPanel2.add(labeladm, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 120, -1));

        labelresp.setForeground(new java.awt.Color(153, 255, 255));
        labelresp.setText(".");
        jPanel2.add(labelresp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 120, -1));

        labeldok.setForeground(new java.awt.Color(153, 255, 255));
        labeldok.setText(".");
        jPanel2.add(labeldok, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 120, -1));

        labelran.setForeground(new java.awt.Color(153, 255, 255));
        labelran.setText("-.");
        jPanel2.add(labelran, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 120, -1));

        labelucr.setForeground(new java.awt.Color(153, 255, 255));
        labelucr.setText(".");
        jPanel2.add(labelucr, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ranActionPerformed
        randevu.setVisible(true);
    }//GEN-LAST:event_ranActionPerformed

    private void admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admActionPerformed
        ad.setVisible(true);    }//GEN-LAST:event_admActionPerformed

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        giris.setVisible(true);
    }//GEN-LAST:event_resActionPerformed

    private void dokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokActionPerformed
        dr.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_dokActionPerformed

    private void ucrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucrActionPerformed
        fy.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ucrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adm;
    private javax.swing.JButton dok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labeladm;
    private javax.swing.JLabel labeladmin;
    private javax.swing.JLabel labeldok;
    private javax.swing.JLabel labelran;
    private javax.swing.JLabel labelres;
    private javax.swing.JLabel labelresp;
    private javax.swing.JLabel labelucr;
    private javax.swing.JButton ran;
    private javax.swing.JButton res;
    private javax.swing.JButton ucr;
    // End of variables declaration//GEN-END:variables
}
