
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.awt.print.Printable;
import java.awt.print.*;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Furkan
 */
public class FaturaYazdirma extends javax.swing.JFrame {

    static ArrayList<fatura> list = new ArrayList();
    DefaultComboBoxModel gun = new DefaultComboBoxModel();
    DefaultComboBoxModel ay = new DefaultComboBoxModel();
    DefaultComboBoxModel yıl = new DefaultComboBoxModel();

    public FaturaYazdirma() {
        initComponents();
        gunbox.setModel(gun);
        aybox.setModel(ay);
        yılbox.setModel(yıl);

        for (int i = 1; i < 32; i++) {
            gun.addElement(i);
        }
        for (int i = 1; i < 13; i++) {
            ay.addElement(i);
        }
        for (int i = 2021; i < 2026; i++) {
            yıl.addElement(i);

        }
    }

    boolean faturaNumarasınınAynısındanVarMı() {
        boolean aynıMı = false;
        for (fatura f : FaturaYazdirma.list) {
            if (f.getFaturano().equals(faturano.getText())) {
                aynıMı = true;
            }
        }
        return aynıMı;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        faturano = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        adres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cinsiyet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        faturatarihi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        telno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        doktorucret = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        odaucret = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ekstraucret = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        doktorad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        toplamucret = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        tc = new javax.swing.JTextField();
        gir = new javax.swing.JButton();
        gunbox = new javax.swing.JComboBox<>();
        aybox = new javax.swing.JComboBox<>();
        yılbox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Fatura No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 87, -1));

        jLabel2.setText("TC");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));
        jPanel1.add(faturano, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 95, 83, -1));

        jLabel3.setText("Hasta ismi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, -1, -1));
        jPanel1.add(ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 145, 83, -1));

        jLabel4.setText("Adres");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, -1, -1));
        jPanel1.add(adres, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 193, 83, -1));

        jLabel5.setText("Cinsiyet");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 248, -1, -1));
        jPanel1.add(cinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 245, 83, -1));

        jLabel6.setText("Fatura Tarihi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 47, -1, -1));

        faturatarihi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturatarihiActionPerformed(evt);
            }
        });
        jPanel1.add(faturatarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 90, 20));

        jLabel7.setText("Hasta İletişim Numarası");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 98, -1, -1));
        jPanel1.add(telno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 170, -1));

        jLabel8.setText("Doktor Ücreti");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 148, -1, -1));
        jPanel1.add(doktorucret, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 170, -1));

        jLabel9.setText("Oda Ücreti");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 196, -1, -1));
        jPanel1.add(odaucret, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 170, -1));

        jLabel10.setText("Ekstra Ücretler");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));
        jPanel1.add(ekstraucret, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 170, -1));

        jLabel11.setText("Doktor Adı");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 301, -1, -1));
        jPanel1.add(doktorad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 170, -1));

        jLabel12.setText("Toplam Ücret");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 353, -1, -1));
        jPanel1.add(toplamucret, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 170, 20));

        print.setBackground(new java.awt.Color(204, 204, 0));
        print.setText("Print Bill");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 559, -1));
        jPanel1.add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 44, 83, -1));

        gir.setBackground(new java.awt.Color(204, 204, 0));
        gir.setText("Gir");
        gir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girActionPerformed(evt);
            }
        });
        jPanel1.add(gir, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 43, -1, -1));

        gunbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", " " }));
        jPanel1.add(gunbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        aybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", " " }));
        jPanel1.add(aybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        yılbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021" }));
        jPanel1.add(yılbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 390, 350));

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void faturatarihiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturatarihiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faturatarihiActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed

        // Fatura Numarası aynı mı kontol etme
        
       
        
        if (faturaNumarasınınAynısındanVarMı()) {
            JOptionPane.showMessageDialog(this, "Fatura numarası veri tabanındaki birisi ile uyuşuyor.\nLütfen farklı fatura numarası giriniz!", "Hata!", JOptionPane.WARNING_MESSAGE);
            return;
        } else { // textarea bölgesine girilen verileri yazdırma
            faturatarihi.setText(gunbox.getSelectedItem() + "/" + aybox.getSelectedItem() + "/" + yılbox.getSelectedItem());
            
            textarea.append("\t FSM HASTANESİ FATURA BİLGİLERİ" +   "\n\n TC NO:" + tc.getText() + "\n\n Fatura NO:" + faturano.getText() + "\n\n İsim:" + ad.getText() + "\n\n Adres:" + adres.getText() + "\n\n Fatura Tarihi:" + faturatarihi.getText()
                    + "\n\n Tel No:" + telno.getText() + "\n\n Doktor Adı:" + doktorad.getText() + "\n\n Oda Ücreti:" + odaucret.getText()
                    + "\n\n Doktor Ücreti:" + doktorucret.getText() + "\n\n Ekstra Ucretler:" + ekstraucret.getText() + "\n\n Toplam Ucret:" + toplamucret.getText() + "\n\n\t FATURA BİLGİLERİ EKTEDİR");

            // Fatura çıktısını almak için yazdırma işlemi
            String printData = textarea.getText();
            PrinterJob job = PrinterJob.getPrinterJob();

            boolean doPrint = job.printDialog();
            if (doPrint) {

                try {
                    job.print();
                } catch (PrinterException e) {

                }
            }

        }


    }//GEN-LAST:event_printActionPerformed

    private void girActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girActionPerformed
        //TC numarasına göre tc ye ait olan hastanın verilerini gerekli sınıflardan arraylist ile getirme
         Random rastgele = new Random();
        
        int sayi=10000+rastgele.nextInt(90001);
        String sayisi=String.valueOf(sayi);
        String faturanumarasi="A"+sayisi;
        faturano.setText(faturanumarasi);
        for (Ucret u : HastaUcretYonetimi.list) {
            for (Hastalar h : HastaYonetimi.list) {
                if (tc.getText().equals(h.getTc())) {
                    ad.setText(h.getHastaad());
                    adres.setText(h.getAdres());
                    cinsiyet.setText(h.getCinsiyet());
                    doktorad.setText(h.getDoktorad());
                    doktorucret.setText(u.getDoktorucreti());
                    odaucret.setText(u.getOdaucreti());
                    ekstraucret.setText(u.getEkstracret());
                    toplamucret.setText(u.getTutar());
                    telno.setText(u.getTelno());

                }
            }

        }
    }//GEN-LAST:event_girActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GöstergePaneli go = new GöstergePaneli();
        go.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturaYazdirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturaYazdirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturaYazdirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturaYazdirma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaturaYazdirma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JTextField adres;
    private javax.swing.JComboBox<String> aybox;
    private javax.swing.JTextField cinsiyet;
    private javax.swing.JTextField doktorad;
    private javax.swing.JTextField doktorucret;
    private javax.swing.JTextField ekstraucret;
    private javax.swing.JTextField faturano;
    private javax.swing.JTextField faturatarihi;
    private javax.swing.JButton gir;
    private javax.swing.JComboBox<String> gunbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField odaucret;
    private javax.swing.JButton print;
    private javax.swing.JTextField tc;
    private javax.swing.JTextField telno;
    private javax.swing.JTextArea textarea;
    private javax.swing.JTextField toplamucret;
    private javax.swing.JComboBox<String> yılbox;
    // End of variables declaration//GEN-END:variables
}
