
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Furkan
 */
public class HastaYonetimi extends javax.swing.JFrame {

    static ArrayList<Hastalar> list = new ArrayList();
    OdaYonetimi o = new OdaYonetimi();
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultComboBoxModel dcm = new DefaultComboBoxModel();
    DefaultComboBoxModel dcm2 = new DefaultComboBoxModel();
    DefaultComboBoxModel dcm3 = new DefaultComboBoxModel();
    DefaultComboBoxModel drbox = new DefaultComboBoxModel();
    DefaultComboBoxModel albox = new DefaultComboBoxModel();

    public HastaYonetimi() {
        initComponents();
        Hastalar h1 = new Hastalar("14934036202", "Furkan Tuluk", "İstanbul-Fatih", "Erkek", "Covid-19", "Mehmet Öz", "Kalp Cerrahı", "102", "2", "A");

        Hastalar h2 = new Hastalar("1165514558", "Mustafa İleri", "İstanbul-Bağcılar", "Erkek", "Covid-19", "Gazi Yaşargil", "Beyin Cerrahı", "103", "3", "B");

        dtm.setColumnIdentifiers(new String[]{"Hasta tc", "Hasta İsmi", "Adres", "Cinsiyet", "Hastalık", "Hasta Doktoru", "Doktor Alanı", "Oda Numarası", "Yatak Numarası", "Kaldığı Tesis"});
        dcm.addElement("");
        dcm2.addElement("");
        dcm3.addElement("");
        for (int i = 100; i < 105; i++) {
            dcm.addElement(i);
        }
        for (int i = 1; i < 9; i++) {
            dcm2.addElement(i);
        }

        dcm3.addElement("A");
        dcm3.addElement("B");
        dcm3.addElement("C");

        box.setModel(dcm);
        box2.setModel(dcm2);
        box3.setModel(dcm3);
        boxdoktor.setModel(drbox);
        jboxalan.setModel(albox);
        table.setModel(dtm);
        list.add(h1);
        list.add(h2);

        Object rowData[] = new Object[10];    //Oluşturulan nesneleri Table kısmına eklemek için 
        for (int i = 0; i < list.size(); i++) {

            rowData[0] = list.get(i).getTc();
            rowData[1] = list.get(i).getHastaad();
            rowData[2] = list.get(i).getAdres();
            rowData[3] = list.get(i).getCinsiyet();
            rowData[4] = list.get(i).getHastalık();
            rowData[5] = list.get(i).getDoktorad();
            rowData[6] = list.get(i).getAlan();
            rowData[7] = list.get(i).getOdano();
            rowData[8] = list.get(i).getYatakno();
            rowData[9] = list.get(i).getBlok();

            dtm.addRow(rowData);

        }

        for (doktorlar d : DoktorYonetimi.dr) {

            drbox.addElement(d.getDoktoradi());
            albox.addElement(d.getUzmanlik());
         
            if(boxdoktor.getSelectedItem().equals(d.getDoktoradi())){
                
                jboxalan.getSelectedItem().equals(d.getUzmanlik());
                
                
            }
        }

    }

    boolean tcNumarasınınAynısındanVarMı() {
        boolean aynıMı = false;
        for (Hastalar h : HastaYonetimi.list) {
            if (h.getTc().equals(tc.getText())) {
                aynıMı = true;
            }
        }
        return aynıMı;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxalan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kaydet = new javax.swing.JButton();
        ara = new javax.swing.JButton();
        temizle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        hastaismi = new javax.swing.JTextField();
        adres = new javax.swing.JTextField();
        hastalık = new javax.swing.JTextField();
        box = new javax.swing.JComboBox<>();
        box2 = new javax.swing.JComboBox<>();
        erkek = new javax.swing.JRadioButton();
        kadın = new javax.swing.JRadioButton();
        guncelle = new javax.swing.JButton();
        kaldır = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        box3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        boxdoktor = new javax.swing.JComboBox<>();
        jboxalan = new javax.swing.JComboBox<>();
        gp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        boxalan.setBackground(new java.awt.Color(102, 102, 255));
        boxalan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Hasta İsmi");
        boxalan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 99, -1, -1));

        jLabel2.setText("Adres");
        boxalan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 175, -1, -1));

        jLabel3.setText("Cinsiyet");
        boxalan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 214, -1, -1));

        jLabel4.setText("Hastalık");
        boxalan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 254, -1, -1));

        jLabel5.setText("Sevk Doktoru");
        boxalan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 99, -1, -1));

        jLabel6.setText("Oda Numarası");
        boxalan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 180, -1, -1));

        jLabel7.setText("Kaldığı Tesis");
        boxalan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 273, -1, -1));

        kaydet.setBackground(new java.awt.Color(102, 102, 255));
        kaydet.setText("Kaydet");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });
        boxalan.add(kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 321, 155, -1));

        ara.setBackground(new java.awt.Color(102, 102, 255));
        ara.setText("Ara");
        ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araActionPerformed(evt);
            }
        });
        boxalan.add(ara, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 321, 157, -1));

        temizle.setBackground(new java.awt.Color(102, 102, 255));
        temizle.setText("Temizle");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });
        boxalan.add(temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 321, 161, -1));

        table.setBackground(new java.awt.Color(102, 102, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        boxalan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 362, 887, 132));

        hastaismi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaismiActionPerformed(evt);
            }
        });
        boxalan.add(hastaismi, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 96, 159, -1));

        adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresActionPerformed(evt);
            }
        });
        boxalan.add(adres, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 172, 159, -1));
        boxalan.add(hastalık, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 251, 82, -1));

        box.setBackground(new java.awt.Color(102, 102, 255));
        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxActionPerformed(evt);
            }
        });
        boxalan.add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 118, -1));

        box2.setBackground(new java.awt.Color(102, 102, 255));
        box2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });
        boxalan.add(box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 118, -1));

        erkek.setBackground(new java.awt.Color(102, 102, 255));
        erkek.setText("Erkek");
        erkek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erkekActionPerformed(evt);
            }
        });
        boxalan.add(erkek, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 210, -1, -1));

        kadın.setBackground(new java.awt.Color(102, 102, 255));
        kadın.setText("Kadın");
        kadın.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kadınActionPerformed(evt);
            }
        });
        boxalan.add(kadın, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 210, -1, -1));

        guncelle.setBackground(new java.awt.Color(102, 102, 255));
        guncelle.setText("Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });
        boxalan.add(guncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 512, 143, -1));

        kaldır.setBackground(new java.awt.Color(102, 102, 255));
        kaldır.setText("Kaldır");
        kaldır.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaldırActionPerformed(evt);
            }
        });
        boxalan.add(kaldır, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 512, 148, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("HASTA YÖNETİM SAYFASI");
        boxalan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel9.setText("Doktor Alanı");
        boxalan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 137, -1, -1));

        jLabel10.setText("Yatak Numarası");
        boxalan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 224, -1, 20));

        box3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxalan.add(box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 118, -1));

        jLabel11.setText("TC ");
        boxalan.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 137, -1, -1));
        boxalan.add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 134, 159, -1));

        boxdoktor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxalan.add(boxdoktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jboxalan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxalan.add(jboxalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, -1));

        gp.setBackground(new java.awt.Color(102, 102, 255));
        gp.setText("GERİ");
        gp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpActionPerformed(evt);
            }
        });
        boxalan.add(gp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxalan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxalan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        String cinsiyet = "";
        String mesaj = "Bu yatak doludur .\nLütfen başka bir oda veya yatak seçiniz. \nEğer tüm oda ve yataklar doluysa başka bloğa bakınız!";
        if (erkek.isSelected()) {
            cinsiyet = erkek.getText();
        } else if (kadın.isSelected()) {
            cinsiyet = kadın.getText();
        }

        try {
            if (tcNumarasınınAynısındanVarMı()) {   // TC numara kontrolü
                JOptionPane.showMessageDialog(this, "TC numaranız veri tabanındaki birisi ile uyuşuyor.\nLütfen doğru girdiğinizden emin olunuz!", "Hata!", JOptionPane.WARNING_MESSAGE);
                return;
            } else {

                for (int i = 0; i < table.getRowCount(); i++) {     // Tabledeki oda yatak blok yerlerine bakarak aynısı var mı yok mu onun kontrolü eğer yoksa eklesin.
                    if (box.getSelectedItem().equals(table.getModel().getValueAt(i, 7)) && box2.getSelectedItem().equals(table.getModel().getValueAt(i, 8)) && box3.getSelectedItem().equals(table.getModel().getValueAt(i, 9))) {
                        JOptionPane.showMessageDialog(this, mesaj, "Uyarı!", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }

                dtm.addRow(new Object[]{tc.getText(), hastaismi.getText(), adres.getText(), cinsiyet, hastalık.getText(), // Table ve Liste ekleme verileri.
                    boxdoktor.getSelectedItem(), jboxalan.getSelectedItem(), box.getSelectedItem(), box2.getSelectedItem(), box3.getSelectedItem()});
                Hastalar h = new Hastalar(tc.getText(), hastaismi.getText(), adres.getText(), cinsiyet, hastalık.getText(), boxdoktor.getSelectedItem().toString(), jboxalan.getSelectedItem().toString(), box.getSelectedItem().toString(), box2.getSelectedItem().toString(), box3.getSelectedItem().toString());
                list.add(h);

                JOptionPane.showMessageDialog(this, "Yeni Hasta Başarıyla Eklenmiştir.");
            }

        } catch (NullPointerException e) {

        } catch (NumberFormatException n) {

        }

    }//GEN-LAST:event_kaydetActionPerformed

    private void araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araActionPerformed
        // Arraylistteki verilerin hepsini table de görme
        try {
            for (int i = table.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
            Object rowData[] = new Object[10];
            for (int i = 0; i < list.size(); i++) {

                rowData[0] = list.get(i).getTc();
                rowData[1] = list.get(i).getHastaad();
                rowData[2] = list.get(i).getAdres();
                rowData[3] = list.get(i).getCinsiyet();
                rowData[4] = list.get(i).getHastalık();
                rowData[5] = list.get(i).getDoktorad();
                rowData[6] = list.get(i).getAlan();
                rowData[7] = list.get(i).getOdano();
                rowData[8] = list.get(i).getYatakno();
                rowData[9] = list.get(i).getBlok();

                dtm.addRow(rowData);

            }
        } catch (ArrayIndexOutOfBoundsException e) {

        }


    }//GEN-LAST:event_araActionPerformed

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed
        for (int i = table.getRowCount() - 1; i >= 0; i--) { // Tüm tableyi temizleme

            dtm.removeRow(i);
        }
    }//GEN-LAST:event_temizleActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        //Tabledeki verileri güncelleme
        int secilisatir = table.getSelectedRow();

        try {
            String tc1 = tc.getText();
            String isim1 = hastaismi.getText();
            String adres1 = adres.getText();
            String cinsiyet1="";
            if (erkek.isSelected()) {
                cinsiyet1 = erkek.getText();
            } else if (kadın.isSelected()) {
                cinsiyet1 = kadın.getText();
            }
            String hastalik1 = hastalık.getText();
            String doktoradi1 = boxdoktor.getSelectedItem().toString();
            String uzman1 = jboxalan.getSelectedItem().toString();
            String odano1 = box.getSelectedItem().toString();
            String yatakno1 = box2.getSelectedItem().toString();
            String tesis1 = box3.getSelectedItem().toString();

            dtm.setValueAt(tc1, secilisatir, 0);
            dtm.setValueAt(isim1, secilisatir, 1);
            dtm.setValueAt(adres1, secilisatir, 2);
            dtm.setValueAt(cinsiyet1, secilisatir, 3);
            dtm.setValueAt(hastalik1, secilisatir, 4);
            dtm.setValueAt(uzman1, secilisatir, 5);
            dtm.setValueAt(doktoradi1, secilisatir, 6);
            dtm.setValueAt(odano1, secilisatir, 7);
            dtm.setValueAt(yatakno1, secilisatir, 8);
            dtm.setValueAt(tesis1, secilisatir, 9);

            JOptionPane.showMessageDialog(this, "Başarıyla Güncellendi");

            if (table.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table boş");
            }
        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_guncelleActionPerformed

    private void kaldırActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaldırActionPerformed
        // Tabledeki verilerin hepsini kaldırma

        try {
            if (table.getSelectedRow() == -1) {
                return;
            }
            String[] seçimler = {"Evet", "Hayır"};
            int seçim = JOptionPane.showOptionDialog(this, "Bu hastayı silmek istediğinize emin misiniz!", "Uyarı!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, seçimler, seçimler[0]);

            if (seçim == 0) {
                dtm.removeRow(table.getSelectedRow());
                  
                for (int i = 0; i < table.getRowCount(); i++) {
                    String tcno= (String)table.getModel().getValueAt(i, 0);
                    for(Hastalar h : list){
                        if(tcno.equals(h.getTc())){
                            list.remove(h);
                        }
                        
                        
                    }
                    
                }

                JOptionPane.showMessageDialog(this, "Hasta silinmiştir!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Silmek istediğiniz hastayı seçiniz!", "Uyarı!", JOptionPane.WARNING_MESSAGE);

            }

        } catch (RuntimeException e) {

        }

    }//GEN-LAST:event_kaldırActionPerformed

    private void hastaismiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaismiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hastaismiActionPerformed

    private void adresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresActionPerformed

    private void boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box2ActionPerformed

    private void erkekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erkekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_erkekActionPerformed

    private void kadınActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kadınActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kadınActionPerformed

    private void gpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpActionPerformed
        GöstergePaneli go = new GöstergePaneli();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaYonetimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adres;
    private javax.swing.JButton ara;
    private javax.swing.JComboBox<String> box;
    private javax.swing.JComboBox<String> box2;
    private javax.swing.JComboBox<String> box3;
    private javax.swing.JPanel boxalan;
    private javax.swing.JComboBox<String> boxdoktor;
    private javax.swing.JRadioButton erkek;
    private javax.swing.JButton gp;
    private javax.swing.JButton guncelle;
    private javax.swing.JTextField hastaismi;
    private javax.swing.JTextField hastalık;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jboxalan;
    private javax.swing.JRadioButton kadın;
    private javax.swing.JButton kaldır;
    private javax.swing.JButton kaydet;
    private javax.swing.JTable table;
    private javax.swing.JTextField tc;
    private javax.swing.JButton temizle;
    // End of variables declaration//GEN-END:variables
}
