
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Furkan
 */
public class HastaUcretYonetimi extends javax.swing.JFrame {

    static ArrayList<Ucret> list = new ArrayList();
    DefaultTableModel dtm = new DefaultTableModel();

    public HastaUcretYonetimi() {
        initComponents();

        dtm.setColumnIdentifiers(new String[]{"Tc", "Ad-Soyad", "Telefon No", "Adres", "Cinsiyet", "Doktor Ücreti", "Oda ücreti", "Ekstra Ücretler", "Toplam Tutar", "Doktor Adı"});

        table.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hastaismi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        adres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        temizle = new javax.swing.JButton();
        telno = new javax.swing.JTextField();
        doktorucreti = new javax.swing.JTextField();
        ekstraucret = new javax.swing.JTextField();
        doktor = new javax.swing.JTextField();
        odaucreti = new javax.swing.JTextField();
        kaydet = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        cinsiyet = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        gir = new javax.swing.JButton();
        tutar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Hasta TC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel1.add(hastaismi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 110, -1));

        jLabel3.setText("Adres");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, -1, -1));

        adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresActionPerformed(evt);
            }
        });
        jPanel1.add(adres, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, -1));

        jLabel4.setText("Cinsiyet");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 259, -1, -1));

        jLabel5.setText("Telefon Numarası");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setText("Doktor Ücreti");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 118, -1, -1));

        jLabel7.setText("Oda Ücreti");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 156, -1, -1));

        jLabel8.setText("Ekstra Ücretler");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 201, -1, -1));

        jLabel9.setText("Taburcu Eden Doktor");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        temizle.setBackground(new java.awt.Color(255, 204, 204));
        temizle.setText("Temizle");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });
        jPanel1.add(temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 347, 127, -1));
        jPanel1.add(telno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 110, 20));

        doktorucreti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorucretiActionPerformed(evt);
            }
        });
        jPanel1.add(doktorucreti, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 115, 108, -1));

        ekstraucret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekstraucretActionPerformed(evt);
            }
        });
        jPanel1.add(ekstraucret, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 198, 108, -1));

        doktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorActionPerformed(evt);
            }
        });
        jPanel1.add(doktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 108, -1));

        odaucreti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odaucretiActionPerformed(evt);
            }
        });
        jPanel1.add(odaucreti, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 153, 108, -1));

        kaydet.setBackground(new java.awt.Color(255, 204, 204));
        kaydet.setText("Kaydet");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });
        jPanel1.add(kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 347, 131, -1));

        sil.setBackground(new java.awt.Color(255, 204, 204));
        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });
        jPanel1.add(sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 347, 129, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 404, 802, 140));

        jLabel10.setText("+90");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        jPanel1.add(cinsiyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("ÜCRET YÖNETİM SAYFASI");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 32, -1, -1));

        jLabel12.setText("Hasta Adı");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, -1, -1));
        jPanel1.add(tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 134, -1));

        gir.setText("Gir");
        gir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girActionPerformed(evt);
            }
        });
        jPanel1.add(gir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        tutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutarActionPerformed(evt);
            }
        });
        jPanel1.add(tutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresActionPerformed

    private void odaucretiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odaucretiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odaucretiActionPerformed

    private void ekstraucretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekstraucretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ekstraucretActionPerformed

    private void doktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doktorActionPerformed

    private void doktorucretiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorucretiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doktorucretiActionPerformed

    private void girActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girActionPerformed
        try {
            for (doktorlar d : DoktorYonetimi.dr) {          //TC numarasına göre tc ye ait olan hastanın verilerini gerekli sınıflardan arraylist ile getirme

                for (Hastalar h : HastaYonetimi.list) {
                    if (tc.getText().equals(h.getTc())) {
                        hastaismi.setText(h.getHastaad());
                        adres.setText(h.getAdres());
                        cinsiyet.setText(h.getCinsiyet());
                        doktor.setText(h.getDoktorad());
                        if (h.getYatakno().equals("6")) {
                            odaucreti.setText("200");
                        } else {
                            odaucreti.setText("150");
                        }
                        if (doktor.getText().equals(d.getDoktoradi())) {
                            doktorucreti.setText(d.getUcret());
                        }

                    }

                }
            }
        } catch (RuntimeException e) {

        }
    }//GEN-LAST:event_girActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        // Arrayliste ve tableye ekleme

        try {
            int a = Integer.parseInt(doktorucreti.getText().toString()) + Integer.parseInt(odaucreti.getText().toString()) + Integer.parseInt(ekstraucret.getText().toString());
            tutar.setText(String.valueOf(a));
            dtm.addRow(new Object[]{tc.getText(), hastaismi.getText(), telno.getText(), adres.getText(), cinsiyet.getText(), doktorucreti.getText(), odaucreti.getText(), ekstraucret.getText(), tutar.getText(), doktor.getText()});
            Ucret u = new Ucret(doktorucreti.getText(), odaucreti.getText(), ekstraucret.getText(), tutar.getText(), telno.getText());
            list.add(u);
        } catch (RuntimeException t) {

        }
    }//GEN-LAST:event_kaydetActionPerformed

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed
        // Tablenin hepsini temizleme
        for (int i = table.getRowCount() - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
    }//GEN-LAST:event_temizleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        //Tablenin seçili satırını silme
        try {
            if (table.getSelectedRow() == -1) {
                return;
            }
            String[] seçimler = {"Evet", "Hayır"};
            int seçim = JOptionPane.showOptionDialog(this, "Silmek istediğinize emin misiniz!", "Uyarı!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, seçimler, seçimler[0]);

            if (seçim == 0) {
                dtm.removeRow(table.getSelectedRow());
                  
                for (int i = 0; i < table.getRowCount(); i++) {
                    String tcno= (String)table.getModel().getValueAt(i, 2);
                    for(Ucret u : list){
                        if(telno.equals(u.getTelno())){
                            list.remove(u);
                        }
                        
                        
                    }
                    
                }

                JOptionPane.showMessageDialog(this, "Silinmiştir!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Silmek istediğinizi seçiniz!", "Uyarı!", JOptionPane.WARNING_MESSAGE);

            }

        } catch (RuntimeException e) {

        }
    }//GEN-LAST:event_silActionPerformed

    private void tutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tutarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GöstergePaneli go = new GöstergePaneli();
        go.setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaUcretYonetimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adres;
    private javax.swing.JTextField cinsiyet;
    private javax.swing.JTextField doktor;
    private javax.swing.JTextField doktorucreti;
    private javax.swing.JTextField ekstraucret;
    private javax.swing.JButton gir;
    private javax.swing.JTextField hastaismi;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kaydet;
    private javax.swing.JTextField odaucreti;
    private javax.swing.JButton sil;
    private javax.swing.JTable table;
    private javax.swing.JTextField tc;
    private javax.swing.JTextField telno;
    private javax.swing.JButton temizle;
    private javax.swing.JTextField tutar;
    // End of variables declaration//GEN-END:variables
}
