
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Furkan
 */
public class OdaYonetimi extends javax.swing.JFrame {
    //Arraylist oluşturma ve veri ekleme

    static ArrayList<Odalar> list = new ArrayList();
    Odalar o1 = new Odalar("100", "6", "A", "200");
    Odalar o2 = new Odalar("101", "8", "A", "150");
    Odalar o3 = new Odalar("102", "6", "A", "200");
    Odalar o4 = new Odalar("103", "8", "A", "150");
    Odalar o5 = new Odalar("104", "6", "A", "200");
    Odalar o6 = new Odalar("100", "6", "B", "200");
    Odalar o7 = new Odalar("101", "8", "B", "150");
    Odalar o8 = new Odalar("102", "6", "B", "200");
    Odalar o9 = new Odalar("103", "8", "B", "150");
    Odalar o10 = new Odalar("104", "6", "B", "200");

    DefaultTableModel dtm = new DefaultTableModel();
    DefaultComboBoxModel dcm = new DefaultComboBoxModel();
    DefaultComboBoxModel dcm2 = new DefaultComboBoxModel();

    public OdaYonetimi() {
        initComponents();
        box.setModel(dcm);
        box2.setModel(dcm2);
        dtm.setColumnIdentifiers(new String[]{"Oda ID", "Oda Numarası", "Tesis", "Ücret", "Toplam Yatak Kapasitesi"});
        dcm.addElement("A tesisi");
        dcm.addElement("B tesisi");
        dcm.addElement("C tesisi");
        table.setModel(dtm);
        for (int i = 100; i < 105; i++) {
            dcm2.addElement(i);
        }
        list.add(o1);
        list.add(o2);
        list.add(o3);
        list.add(o4);
        list.add(o5);
        list.add(o6);
        list.add(o7);
        list.add(o8);
        list.add(o9);
        list.add(o10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ucret = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        yataksayisi = new javax.swing.JTextField();
        kaydet = new javax.swing.JButton();
        ara = new javax.swing.JButton();
        temizle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        güncelle = new javax.swing.JButton();
        kaldir = new javax.swing.JButton();
        box = new javax.swing.JComboBox<>();
        box2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        odanumarasi = new javax.swing.JTextField();
        tesis1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Oda Numarası");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel2.setText("Tıbbi Tesis");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel3.setText("Ücret");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 98, -1, -1));
        jPanel1.add(ucret, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 95, 110, -1));

        jLabel4.setText("Toplam Yatak");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 153, -1, -1));
        jPanel1.add(yataksayisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 110, -1));

        kaydet.setBackground(new java.awt.Color(255, 255, 204));
        kaydet.setText("Kaydet");
        kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetActionPerformed(evt);
            }
        });
        jPanel1.add(kaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 246, 77, -1));

        ara.setBackground(new java.awt.Color(255, 255, 204));
        ara.setText("Ara");
        ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araActionPerformed(evt);
            }
        });
        jPanel1.add(ara, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 246, 80, -1));

        temizle.setBackground(new java.awt.Color(255, 255, 204));
        temizle.setText("Temizle");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });
        jPanel1.add(temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 246, 82, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 312, 631, 129));

        güncelle.setBackground(new java.awt.Color(255, 255, 204));
        güncelle.setText("Güncelle");
        güncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelleActionPerformed(evt);
            }
        });
        jPanel1.add(güncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 508, -1, -1));

        kaldir.setBackground(new java.awt.Color(255, 255, 204));
        kaldir.setText("Kaldır");
        kaldir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaldirActionPerformed(evt);
            }
        });
        jPanel1.add(kaldir, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 508, -1, -1));

        box.setBackground(new java.awt.Color(255, 255, 204));
        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A" }));
        jPanel1.add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 78, -1));

        box2.setBackground(new java.awt.Color(255, 255, 204));
        box2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100" }));
        jPanel1.add(box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 78, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("ODA YÖNETİMİ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 11, 176, -1));

        odanumarasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odanumarasiActionPerformed(evt);
            }
        });
        jPanel1.add(odanumarasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, -1));
        jPanel1.add(tesis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 70, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_araActionPerformed

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed
        // Tabledeki verileri götürme
        for (int i = table.getRowCount() - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
    }//GEN-LAST:event_temizleActionPerformed

    private void güncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelleActionPerformed
        int secilisatir = table.getSelectedRow();

        //Tabledeki verileri güncelleme
        try {
            String odano = box2.getSelectedItem().toString();
            String tesis = box.getSelectedItem().toString();
            String ucret1 = ucret.getText();
            String yatak = yataksayisi.getText();
           

            dtm.setValueAt(odano, secilisatir, 0);
            dtm.setValueAt(tesis, secilisatir, 1);
            dtm.setValueAt(ucret, secilisatir, 2);
            dtm.setValueAt(yatak, secilisatir, 3);

            JOptionPane.showMessageDialog(this, "Başarıyla Güncellendi");

            
            ucret.setText("");
            yataksayisi.setText("");

            if (table.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table boş");
            }
        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_güncelleActionPerformed

    private void kaldirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaldirActionPerformed
        // Seçili satırı silme
        if (table.getSelectedRow() == -1) {
            return;
        }
        String[] seçimler = {"Evet", "Hayır"};
        int seçim = JOptionPane.showOptionDialog(this, "Bu Odayı silmek istediğinize emin misiniz!", "Uyarı!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, seçimler, seçimler[0]);

        if (seçim == 0) {
            dtm.removeRow(table.getSelectedRow());

            JOptionPane.showMessageDialog(this, "Oda silinmiştir!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Silmek istediğiniz Odayı seçiniz!", "Uyarı!", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_kaldirActionPerformed

    private void kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetActionPerformed
        // Verileri arrayliste ve tableye ekleme
        dcm2.addElement(odanumarasi.getText());
        dcm.addElement(tesis1.getText());

        // Burada oda numaarası çiftse yatak sayisini ona göre verme ve ücreti belirleme
        if (Integer.parseInt(box2.getSelectedItem().toString()) == 0) {
            ucret.setText("0");
        }
        if (Integer.parseInt(box2.getSelectedItem().toString()) % 2 == 0) {
            yataksayisi.setText("6");
        } else {
            yataksayisi.setText("8");
        }
        if (yataksayisi.getText().equals("6")) {
            ucret.setText("200");
        } else {
            ucret.setText("150");
        }
        JOptionPane.showMessageDialog(this, "Oda başarıyla eklenmiştir!", "Uyarı!", JOptionPane.WARNING_MESSAGE);

        Odalar o = new Odalar(box2.getSelectedItem().toString(), yataksayisi.getText(), box.getSelectedItem().toString(), ucret.getText()); //Arrayliste ekleme
        list.add(o);
        dtm.addRow(new Object[]{table.getRowCount(), box2.getSelectedItem(), box.getSelectedItem(), ucret.getText(), yataksayisi.getText()}); //Tableye ekleme
    }//GEN-LAST:event_kaydetActionPerformed

    private void odanumarasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odanumarasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odanumarasiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GöstergePaneli go = new GöstergePaneli();
        go.setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OdaYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OdaYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OdaYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OdaYonetimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OdaYonetimi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ara;
    private javax.swing.JComboBox<String> box;
    private javax.swing.JComboBox<String> box2;
    private javax.swing.JButton güncelle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kaldir;
    private javax.swing.JButton kaydet;
    private javax.swing.JTextField odanumarasi;
    private javax.swing.JTable table;
    private javax.swing.JButton temizle;
    private javax.swing.JTextField tesis1;
    private javax.swing.JTextField ucret;
    private javax.swing.JTextField yataksayisi;
    // End of variables declaration//GEN-END:variables
}
