
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Furkan
 */
public class ResepsiyonGorevlisi extends javax.swing.JFrame {

    ResepsiyonlariGoruntule rg = new ResepsiyonlariGoruntule();

    public ResepsiyonGorevlisi() {
        initComponents();
        jRadioButtonErkek.setSelected(true);
    }

    boolean desenKontrol(String desenMetni, String icindeDesenArananMetin) {  // Karakter Kontrolü yapmak için
        Pattern desen = Pattern.compile(desenMetni);
        Matcher arama = desen.matcher(icindeDesenArananMetin);
        return arama.find();

    }

    boolean tcNumarasınınAynısındanVarMı() {    //Tc numaralının kontrolünü yapmak için
        boolean aynıMı = false;
        for (Resepsiyon r : ResepsiyonlariGoruntule.list) {
            if (r.getTc().equals(jTextFieldTC.getText())) {
                aynıMı = true;
            }
        }
        return aynıMı;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAd = new javax.swing.JTextField();
        jTextFieldSoyad = new javax.swing.JTextField();
        jTextFieldTC = new javax.swing.JTextField();
        jTextFieldTel = new javax.swing.JTextField();
        jTextFieldYaş = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        ekle = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonErkek = new javax.swing.JRadioButton();
        jRadioButtonKadın = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        kullaniciadi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sifre = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("İsim");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel2.setText("Soyisim");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel6.setText("Telefon No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 155, 60, -1));

        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 231, -1, -1));

        jLabel4.setText("Yaş");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 193, -1, -1));

        jLabel5.setText("Tc");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 124, 20, -1));

        jTextFieldAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 239, -1));

        jTextFieldSoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoyadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 240, -1));

        jTextFieldTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTCActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 240, -1));

        jTextFieldTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 237, -1));

        jTextFieldYaş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYaşActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldYaş, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 237, -1));

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 237, -1));

        ekle.setBackground(new java.awt.Color(153, 153, 153));
        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });
        jPanel1.add(ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 381, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("RESEPSİYON GÖREVLİSİ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 301, -1));

        jLabel8.setText("Cinsiyet");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jRadioButtonErkek.setText("Erkek");
        jPanel1.add(jRadioButtonErkek, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        jRadioButtonKadın.setText("Kadın");
        jPanel1.add(jRadioButtonKadın, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        jLabel9.setText("Kullanıcı Adı");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 269, -1, -1));
        jPanel1.add(kullaniciadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 237, -1));

        jLabel10.setText("Şifre");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 304, -1, -1));
        jPanel1.add(sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdActionPerformed


    }//GEN-LAST:event_jTextFieldAdActionPerformed

    private void jTextFieldSoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoyadActionPerformed

    }//GEN-LAST:event_jTextFieldSoyadActionPerformed

    private void jTextFieldTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTCActionPerformed

    }//GEN-LAST:event_jTextFieldTCActionPerformed

    private void jTextFieldTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelActionPerformed

    }//GEN-LAST:event_jTextFieldTelActionPerformed

    private void jTextFieldYaşActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldYaşActionPerformed


    }//GEN-LAST:event_jTextFieldYaşActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed

        if (jTextFieldAd.getText().isEmpty() || desenKontrol("[^A-z\\s]", jTextFieldAd.getText())) {                              // Ad sadece harflerden
            JOptionPane.showMessageDialog(this, "Lütfen adınızı düzgün giriniz!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (jTextFieldSoyad.getText().isEmpty() || desenKontrol("[^A-z\\s]", jTextFieldSoyad.getText())) {                 // soyad sadece harflerden
            JOptionPane.showMessageDialog(this, "Lütfen soyadınızı düzgün giriniz!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (jTextFieldTC.getText().isEmpty() || desenKontrol("[^0-9]", jTextFieldTC.getText()) || jTextFieldTC.getText().length() != 11) {    // TC 11 hane ve rakam
            JOptionPane.showMessageDialog(this, "Lütfen tc no'da sadece rakam kullanınız!\nAyrıca 11 basamaklı olmalı!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (jTextFieldTel.getText().isEmpty() || jTextFieldTel.getText().length() != 10 || desenKontrol("[^0-9]", jTextFieldTel.getText())) { // Telefon 10 hane ve rakam
            JOptionPane.showMessageDialog(this, "Telefon numarası 10 basamaklı ve sadece rakamdan oluşmalıdır!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (jTextFieldYaş.getText().isEmpty() || Integer.parseInt(jTextFieldYaş.getText()) < 18) {                                              // Yaş 18den büyük 
            JOptionPane.showMessageDialog(this, "18 yaşından küçükler hesap oluşturamazlar!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (jTextFieldEmail.getText().isEmpty() || !desenKontrol("[A-Za-z0-9]+[@][A-Za-z0-9]+(.com)", jTextFieldEmail.getText())) {              //maile uygun format
            JOptionPane.showMessageDialog(this, "Lütfen emaili düzgün bir şekilde giriniz!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
            return;
        }  else if (tcNumarasınınAynısındanVarMı()) {                                                                                               
            JOptionPane.showMessageDialog(this, "TC numaranız veri tabanındaki birisi ile uyuşuyor.\nLütfen doğru girdiğinizden emin olunuz!", "Hata!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String cinsiyet = "";
        if (jRadioButtonErkek.isSelected()) {
            cinsiyet = "erkek";
        } else if (jRadioButtonKadın.isSelected()) {
            cinsiyet = "kadın";
        }

        

        String[] seçimler = {"Evet", "Hayır"};
        int seçim = JOptionPane.showOptionDialog(rootPane, "Bu bilgilerinizle kaydolmak istediğinize emin misiniz?", "Uyarı!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, seçimler, seçimler[0]);

        if (seçim == 0) {
            Resepsiyon r = new Resepsiyon(jTextFieldAd.getText(), jTextFieldSoyad.getText(), jTextFieldEmail.getText(), cinsiyet,
                    jTextFieldTel.getText(), jTextFieldTC.getText(), Integer.parseInt(jTextFieldYaş.getText()), kullaniciadi.getText(), sifre.getText());

     
            
            
            JOptionPane.showMessageDialog(this, "İşleminiz başarıyla tanımlanmıştır!", "Tebrikler!", JOptionPane.INFORMATION_MESSAGE);

            System.out.println("kullanıcılar: " + ResepsiyonlariGoruntule.list);
            System.out.println(r.getAd() + " " + r.getSoyad() + " " + r.getKullanıcıAdı() + " " + r.getŞifre());
                   rg.list.add(r);
                   
            Object rowData[] = new Object[9];
            
            for (int i = 0; i < rg.list.size(); i++) {
                rg.list.get(i).getAd();
                rg.list.get(i).getSoyad();
                rg.list.get(i).getEmail();
                rg.list.get(i).getCinsiyet();
                rg.list.get(i).getTel();
                rg.list.get(i).getTc();
                rg.list.get(i).getYaş();
                rg.list.get(i).getKullanıcıAdı();
                rg.list.get(i).getŞifre();
                
                
                rg.dtm.addRow(rowData);
                
                
            }
            
            
            return;
        } else if (seçim == 1) {
            JOptionPane.showMessageDialog(this, "İşleminiz iptal edilmiştir!", "Uyarı", JOptionPane.INFORMATION_MESSAGE);
            rg.dtm.addRow(new Object[]{jTextFieldAd.getText(), jTextFieldSoyad.getText(), jTextFieldEmail.getText(), cinsiyet,
                jTextFieldTel.getText(), jTextFieldTC.getText(), Integer.parseInt(jTextFieldYaş.getText()), kullaniciadi.getText(), sifre.getText()});
        }


    }//GEN-LAST:event_ekleActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonGorevlisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonGorevlisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonGorevlisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonGorevlisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepsiyonGorevlisi().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonErkek;
    private javax.swing.JRadioButton jRadioButtonKadın;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAd;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldSoyad;
    private javax.swing.JTextField jTextFieldTC;
    private javax.swing.JTextField jTextFieldTel;
    private javax.swing.JTextField jTextFieldYaş;
    private javax.swing.JTextField kullaniciadi;
    private javax.swing.JTextField sifre;
    // End of variables declaration//GEN-END:variables
}
