
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Furkan
 */
public class ResepsiyonlariGoruntule extends javax.swing.JFrame {

    static ArrayList<Resepsiyon> list = new ArrayList();
    Resepsiyon r1 = new Resepsiyon("Furkan", "Tuluk", "f80@gmail.com", "erkek", "5389741638", "14934036202", 24, "furkan", "12345");
    Resepsiyon r2 = new Resepsiyon("Batu", "Bozca", "b01@gmail.com", "erkek", "5396171388", "1165514558", 23, "batu", "123456");
    DefaultTableModel dtm = new DefaultTableModel();

    public ResepsiyonlariGoruntule() {
        initComponents();
        dtm.setColumnIdentifiers(new String[]{"Ad", "Soyad", "Email", "Cinsyet", "Telefon", "TC", "Yaş"});
        Jtable.setModel(dtm);
        list.add(r1);
        list.add(r2);

        
        
        Object rowData[] = new Object[7];      // ArrayListdeki verileri table'ye ekleme 
        for (int i = 0; i < list.size(); i++) {

            rowData[0] = list.get(i).getAd();
            rowData[1] = list.get(i).getSoyad();
            rowData[2] = list.get(i).getEmail();
            rowData[3] = list.get(i).getCinsiyet();
            rowData[4] = list.get(i).getTel();
            rowData[5] = list.get(i).getTc();
            rowData[6] = list.get(i).getYaş();

            dtm.addRow(rowData);

        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtable = new javax.swing.JTable();
        sil = new javax.swing.JButton();
        çik = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Jtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 173));

        sil.setBackground(new java.awt.Color(255, 153, 0));
        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });
        jPanel1.add(sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 110, -1));

        çik.setBackground(new java.awt.Color(255, 153, 0));
        çik.setText("Çık");
        çik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                çikActionPerformed(evt);
            }
        });
        jPanel1.add(çik, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 117, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("RESEPSİYOLARI GÖRÜNTÜLEME SAYFASI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 452, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        try {
            if (Jtable.getSelectedRow() == -1) {
                return;
            }
            String[] seçimler = {"Evet", "Hayır"};
            int seçim = JOptionPane.showOptionDialog(this, "Bu resepsiyonu silmek istediğinize emin misiniz!", "Uyarı!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, seçimler, seçimler[0]);

            if (seçim == 0) {
                dtm.removeRow(Jtable.getSelectedRow());
                list.remove(Jtable.getSelectedRow());

                JOptionPane.showMessageDialog(this, "Resepsioyn silinmiştir!", "Uyarı!", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Silmek istediğiniz Resepsiyonu seçiniz!", "Uyarı!", JOptionPane.WARNING_MESSAGE);

            }

        } catch (RuntimeException e) {

        }


    }//GEN-LAST:event_silActionPerformed

    private void çikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_çikActionPerformed

        this.dispose();


    }//GEN-LAST:event_çikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonlariGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonlariGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonlariGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResepsiyonlariGoruntule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResepsiyonlariGoruntule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtable;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sil;
    private javax.swing.JButton çik;
    // End of variables declaration//GEN-END:variables
}
